CONVERY_FILE_EXT = ".json"
SERVER_HOST = "127.0.0.1"
SERVER_PORT = 3000
SERVER_URL = f"wss://convey.ahmedkaremmousa.com/ws"
WS_CONNECTION_WAIT = 15

CLIENT_PORT = 47987
CLIENT_HOST = "0.0.0.0"

DATEIME_FORMAT = "%Y-%m-%H %M-%S-%f"
